<?php
require __DIR__ . '/includes/bootstrap.php';
$pageTitle = 'Electronic Transactions Policy — ' . SITE_NAME;
$pageDescription = 'How RVZ Personnel Services relies on the Electronic Communications and Transactions Act for e-signatures, electronic contracts and online notices.';
require __DIR__ . '/includes/header.php';
?>
<div class="row justify-content-center"><div class="col-lg-9">
<h1 class="mb-1">Electronic Transactions Policy</h1>
<p class="text-muted mb-4">Electronic Communications and Transactions Act 25 of 2002 ("ECTA") — Last updated: <?= date('F Y') ?></p>

<p>ECTA gives legal recognition to electronic documents, signatures, and contracts in South Africa. This policy
explains how <?= h(COMPANY_LEGAL_NAME) ?> ("RVZ") relies on it.</p>

<h5 class="mt-4">1. Electronic signatures</h5>
<p>Recruiter Service Level Agreements (SLAs) on this Platform are signed electronically — a typed full name,
a checkbox confirming agreement, a timestamp, and your IP address, recorded and stamped onto a generated PDF copy
emailed to you. This constitutes a valid electronic signature under ECTA section 13, since neither party has
required the more stringent "advanced electronic signature" for this type of agreement.</p>

<h5 class="mt-4">2. Electronic contract formation</h5>
<p>By ticking a checkbox and clicking a button to accept our <a href="<?= h(base_url('terms-and-conditions.php')) ?>">Terms
and Conditions</a>, sign an SLA, or complete a purchase, you are entering into a binding electronic agreement. Under
ECTA section 22, an agreement is not without legal force merely because it was concluded electronically.</p>

<h5 class="mt-4">3. Data messages as evidence</h5>
<p>Records generated by the Platform (account activity logs, application timestamps, signed SLA PDFs, payment
confirmations) are "data messages" under ECTA and are admissible as evidence of the transactions they record,
to the extent permitted by law.</p>

<h5 class="mt-4">4. Automated transactions</h5>
<p>Some processes on this Platform are automated (for example, account creation, job-listing credit deduction on
posting, and payment confirmation via Paystack webhooks). Under ECTA section 20, an agreement concluded partly or
wholly through such automated processes is not invalid merely because no natural person reviewed each individual
step.</p>

<h5 class="mt-4">5. Consumer protection for electronic transactions</h5>
<p>Where you interact with RVZ as a consumer (rather than as a business recruiter), ECTA Chapter VII's consumer
protection provisions — such as our obligation to make certain information available before you conclude a
transaction — are complied with through this Platform's published legal pages, pricing information, and checkout
flow. Candidates never pay to use the Platform, so no consumer transaction arises from browsing or applying for
jobs.</p>

<h5 class="mt-4">6. Unsolicited communications</h5>
<p>Consistent with ECTA section 45, any marketing email or newsletter from RVZ includes a clear way to opt out,
and we do not send unsolicited commercial communications to anyone who has unsubscribed or never opted in.</p>

<h5 class="mt-4">7. Questions</h5>
<p><a href="<?= h(base_url('contact-us.php')) ?>">Contact us</a> with any questions about how we rely on ECTA for
electronic signatures, contracts, or records.</p>
</div></div>
<?php require __DIR__ . '/includes/footer.php'; ?>
